CREATE OR REPLACE PROCEDURE PL (CADENA VARCHAR2) AS
BEGIN
 DBMS_OUTPUT.PUT_LINE(CADENA);
END PL;
/
DROP SEQUENCE SQ_CORR;
CREATE SEQUENCE SQ_CORR;

CREATE OR REPLACE FUNCTION FN_UNIDAD(IDE NUMBER)RETURN VARCHAR2 IS 
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT U.NOMBRE
INTO L_NOMBRE
FROM UNIDAD U JOIN MEDICO M ON U.UNI_ID = M.UNI_ID
WHERE M.MED_RUT = IDE;
RETURN L_NOMBRE;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_ESPECIALIDAD(IDE NUMBER)RETURN VARCHAR2 IS 
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT E.NOMBRE
INTO L_NOMBRE
FROM ESPECIALIDAD E JOIN MEDICO M ON E.ESP_ID = M.ESP_ID
WHERE M.MED_RUT = IDE;
RETURN L_NOMBRE;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_NOMBREMED(IDE NUMBER)RETURN VARCHAR2 IS 
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT M.PNOMBRE ||' '||M.SNOMBRE|| ' '|| M.APATERNO||' '|| M.AMATERNO
INTO L_NOMBRE
FROM MEDICO M
WHERE M.MED_RUT = IDE;
RETURN L_NOMBRE;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_CARGO(IDE NUMBER)RETURN VARCHAR2 IS 
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT C.NOMBRE
INTO L_NOMBRE
FROM CARGO C JOIN MEDICO M ON C.CAR_ID = M.CAR_ID
WHERE M.MED_RUT = IDE;
RETURN L_NOMBRE;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_PACIENTENOM(IDE NUMBER)RETURN VARCHAR2 IS 
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT P.PNOMBRE ||' '||P.SNOMBRE|| ' '|| P.APATERNO||' '|| P.AMATERNO
INTO L_NOMBRE
FROM PACIENTE P
WHERE P.PAC_RUT = IDE;
RETURN L_NOMBRE;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/


CREATE OR REPLACE FUNCTION FN_TIPOSALUD(IDE NUMBER)RETURN VARCHAR2 IS 
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT TS.DESCRIPCION ||' '|| S.DESCRIPCION
INTO L_NOMBRE
FROM TIPO_SALUD TS JOIN SALUD S ON TS.TIPO_SAL_ID = S.TIPO_SAL_ID
JOIN PACIENTE P ON S.SAL_ID = P.SAL_ID
WHERE P.PAC_RUT = IDE;

RETURN L_NOMBRE;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/


CREATE OR REPLACE PROCEDURE PRO_ATENCION(MES NUMBER, AÑO NUMBER)IS
CURSOR C1 IS
SELECT *
FROM ATENCION
WHERE EXTRACT(MONTH FROM FECHA_ATENCION)= MES AND
EXTRACT(YEAR FROM FECHA_ATENCION)= AÑO 
ORDER BY ATE_ID;


L_VAL_NUM_A NUMBER;
L_VAL_FEC_A DATE;
L_VAL_HOR_A ATENCION.HR_ATENCION%TYPE;
L_VAL_UNI_A VARCHAR2(200);
L_VAL_ESP_A VARCHAR2(200);
L_VAL_NOM_M VARCHAR2(200);
L_VAL_CAR_M VARCHAR2(200);
L_VAL_NOM_P VARCHAR2(200);
L_VAL_TSS_P VARCHAR2(200);
L_DIFERENCIA_A NUMBER;
L_COSTO_PAGO NUMBER;
L_TIPO_SALUD VARCHAR2(200);
L_MONTO_ATEN NUMBER;
L_VAL_ATENCION NUMBER;
L_PORC_TERC NUMBER;
L_VAL_DESC_TIR NUMBER;
L_VAL_COSTO NUMBER;
L_VAL_FECHA_GRABACION DATE;
L_FECHA_PROCESO_MES VARCHAR2(100);
L_VAL_DESC_COS NUMBER; 
L_VAL_DESC NUMBER;

BEGIN
DELETE FROM ATENCIONES_MEDICAS_MENSUALES;
FOR R1 IN C1 LOOP
L_VAL_NUM_A := R1.ATE_ID;
L_VAL_FEC_A := R1.FECHA_ATENCION;
L_VAL_HOR_A := R1.HR_ATENCION;
L_VAL_UNI_A := FN_UNIDAD(R1.MED_RUT);
L_VAL_ESP_A := FN_ESPECIALIDAD(R1.MED_RUT);
L_VAL_NOM_M := FN_NOMBREMED(R1.MED_RUT);
L_VAL_CAR_M := FN_CARGO(R1.MED_RUT);
L_VAL_NOM_P := FN_PACIENTENOM(R1.PAC_RUT);
L_VAL_TSS_P :=FN_TIPOSALUD(R1.PAC_RUT);
L_VAL_COSTO := R1.COSTO;
L_VAL_FECHA_GRABACION := SYSDATE;
L_FECHA_PROCESO_MES := MES||'/'|| AÑO;

BEGIN
SELECT EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM FECHA_NACIMIENTO)
INTO L_DIFERENCIA_A
FROM PACIENTE 
WHERE PAC_RUT = R1.PAC_RUT;

SELECT S.DESCRIPCION,S.COSTO_PAGO/100
INTO L_TIPO_SALUD ,L_COSTO_PAGO
FROM TIPO_SALUD TS JOIN SALUD S ON TS.TIPO_SAL_ID = S.TIPO_SAL_ID
JOIN PACIENTE P ON S.SAL_ID = P.SAL_ID
WHERE P.PAC_RUT = R1.PAC_RUT;

SELECT MONTO_ATENCION
INTO L_MONTO_ATEN
FROM PAGO_ATENCION
WHERE ATE_ID = R1.ATE_ID;
END;

BEGIN
SELECT PORCENTAJE_DESCTO/100
INTO L_PORC_TERC
FROM PORC_DESCTO_3RA_EDAD
WHERE L_DIFERENCIA_A BETWEEN ANNO_INI AND ANNO_TER;
EXCEPTION
WHEN NO_DATA_FOUND THEN
L_PORC_TERC :=0;
END; 
 
L_VAL_DESC_TIR := ROUND(L_MONTO_ATEN*L_PORC_TERC);
L_VAL_DESC_COS := ROUND(L_MONTO_ATEN*L_COSTO_PAGO);
L_VAL_DESC := L_VAL_DESC_COS+L_VAL_DESC_TIR;
L_VAL_ATENCION := ROUND((L_MONTO_ATEN-L_VAL_DESC_TIR)*L_COSTO_PAGO);

BEGIN
UPDATE PAGO_ATENCION
SET MONTO_A_CANCELAR = L_VAL_ATENCION
WHERE ATE_ID = R1.ATE_ID;

UPDATE PAGO_ATENCION
SET OBS_PAGO = L_TIPO_SALUD
WHERE ATE_ID = R1.ATE_ID;
END;

BEGIN
INSERT INTO ATENCIONES_MEDICAS_MENSUALES
VALUES(SQ_CORR.NEXTVAL,L_FECHA_PROCESO_MES,L_VAL_NUM_A,L_VAL_FEC_A,
L_VAL_HOR_A,L_VAL_UNI_A,L_VAL_ESP_A,L_VAL_NOM_M,L_VAL_CAR_M,L_VAL_NOM_P,
L_VAL_TSS_P,L_VAL_DESC,L_VAL_COSTO,L_VAL_ATENCION,L_VAL_FECHA_GRABACION);
END;


END LOOP;
END;

/

EXEC PRO_ATENCION(1,2013);

