CREATE OR REPLACE PROCEDURE PL (CADENA VARCHAR2) AS
BEGIN
 DBMS_OUTPUT.PUT_LINE(CADENA);
END PL;
/


DROP SEQUENCE SQ_CORR;

CREATE OR REPLACE FUNCTION FN_LIBRO(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);
BEGIN
SELECT T.TITULO
INTO L_NOMBRE
FROM TITULO T JOIN PRESTAMO P 
ON T.TITULOID = P.TITULOID
WHERE T.TITULOID = IDE;

RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_EDITORIAL(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);

BEGIN

SELECT E.DESCRIPCION
INTO L_NOMBRE
FROM EDITORIAL E JOIN TITULO T ON E.EDITORIALID = T.EDITORIALID
WHERE T.TITULOID = IDE;

RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_AUTOR(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);

BEGIN

SELECT A.NOMBRE||' ' ||A.APELLIDOS
INTO L_NOMBRE
FROM AUTOR A JOIN TITULO T ON A.TITULOID = T.TITULOID
WHERE T.TITULOID = IDE;

RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_ALUMNO(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);

BEGIN

SELECT A.NOMBRE || ' '|| A.APATERNO ||' '|| A.AMATERNO
INTO L_NOMBRE
FROM ALUMNO A JOIN PRESTAMO P ON A.ALUMNOID = P.ALUMNOID
WHERE P.ALUMNOID = IDE;
 
RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_ESCUELA(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);

BEGIN

SELECT E.DESCRIPCION
INTO L_NOMBRE
FROM ESCUELA E JOIN CARRERA C ON E.ESCUELAID = C.ESCUELAID
JOIN ALUMNO A ON C.CARRERAID = A.CARRERAID 
JOIN PRESTAMO P ON A.ALUMNOID = P.ALUMNOID
WHERE P.ALUMNOID = IDE;
 
RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/



CREATE OR REPLACE FUNCTION FN_CARRERA(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);

BEGIN

SELECT C.DESCRIPCION
INTO L_NOMBRE
FROM CARRERA C JOIN ALUMNO A ON C.CARRERAID = A.CARRERAID 
JOIN PRESTAMO P ON A.ALUMNOID = P.ALUMNOID
WHERE P.ALUMNOID = IDE;
 
RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_EMPLEADO(IDE NUMBER)RETURN VARCHAR IS
L_NOMBRE VARCHAR2(200);

BEGIN

SELECT E.NOMBRE || ' '|| E.APATERNO ||' '|| E.AMATERNO
INTO L_NOMBRE
FROM EMPLEADO E JOIN PRESTAMO P ON E.EMPLEADOID = P.EMPLEADOID
WHERE P.EMPLEADOID = IDE;
 
RETURN L_NOMBRE;

EXCEPTION
WHEN TOO_MANY_ROWS THEN
RETURN L_NOMBRE;
END;
/



CREATE OR REPLACE PROCEDURE PRO_PRESTAMO(MES NUMBER, AÑO NUMBER) IS

CURSOR C1 IS 
SELECT *
FROM PRESTAMO
WHERE 
EXTRACT(MONTH FROM FECHA_INICIO)= MES AND
EXTRACT(YEAR FROM FECHA_INICIO)= AÑO
ORDER BY FECHA_INICIO;

L_VAL_NOM_L VARCHAR2(200);
L_VAL_EDT_L VARCHAR2(200);
L_VAL_AUT_L VARCHAR2(200);
L_VAL_ALU_L VARCHAR2(200);
L_VAL_ESC_L VARCHAR2(200);
L_VAL_CAR_L VARCHAR2(200);
L_VAL_EMP_L VARCHAR2(200);
L_DIA_MIN NUMBER;
L_DIA_MAX NUMBER;
L_FECHA_PROCESO VARCHAR2(100);
L_FECHA_PROCESO_MES VARCHAR2(100);
L_FECHA_PRES PRESTAMO.FECHA_INICIO%TYPE;
L_FECHA_DEV  PRESTAMO.FECHA_TERMINO%TYPE;
L_FECHA_DEV_A PRESTAMO.FECHA_ENTREGA%TYPE;
L_DIAS_ATRASO NUMBER;
L_MULTA NUMBER;
L_VAL_FECHA_GRABACION DATE;


BEGIN
DELETE FROM PRESTAMOS_LIBROS_MENSUALES;

FOR R1 IN C1 LOOP
BEGIN 
SELECT MIN(EXTRACT (DAY FROM FECHA_INICIO)),MAX(EXTRACT (DAY FROM FECHA_INICIO))
INTO L_DIA_MIN,L_DIA_MAX
FROM PRESTAMO
WHERE 
EXTRACT(MONTH FROM FECHA_INICIO)= MES AND
EXTRACT(YEAR FROM FECHA_INICIO)= AÑO
ORDER BY FECHA_INICIO;
END;
L_FECHA_PROCESO := L_DIA_MIN||'/'||L_DIA_MAX||'-'||MES||'-'||AÑO;
L_FECHA_PROCESO_MES := MES||'/'|| AÑO;

L_VAL_NOM_L := FN_LIBRO(R1.TITULOID);
L_VAL_EDT_L := FN_EDITORIAL(R1.TITULOID);
L_VAL_AUT_L := FN_AUTOR(R1.TITULOID);
L_VAL_ALU_L := FN_ALUMNO(R1.ALUMNOID);
L_VAL_ESC_L := FN_ESCUELA(R1.ALUMNOID);
L_VAL_CAR_L := FN_CARRERA(R1.ALUMNOID);
L_VAL_EMP_L := FN_EMPLEADO(R1.EMPLEADOID);
L_FECHA_PRES := R1.FECHA_INICIO;
L_FECHA_DEV := R1.FECHA_TERMINO;
L_FECHA_DEV_A := R1.FECHA_ENTREGA;
L_MULTA := NVL(R1.MULTA,0);
L_VAL_FECHA_GRABACION := SYSDATE;


BEGIN 
SELECT FECHA_ENTREGA - FECHA_TERMINO
INTO L_DIAS_ATRASO
FROM PRESTAMO
WHERE PRESTAMOID = R1.PRESTAMOID AND FECHA_ENTREGA - FECHA_TERMINO > 0;
EXCEPTION
WHEN NO_DATA_FOUND THEN  
L_DIAS_ATRASO :=0;
END;

BEGIN
INSERT INTO PRESTAMOS_LIBROS_MENSUALES
VALUES(SQ_CORR.NEXTVAL,L_FECHA_PROCESO_MES,L_VAL_NOM_L,
L_VAL_EDT_L,L_VAL_AUT_L,L_VAL_ALU_L,
L_VAL_ESC_L,L_VAL_CAR_L,L_VAL_EMP_L,L_FECHA_PRES,L_FECHA_DEV,
L_FECHA_DEV_A,L_DIAS_ATRASO,L_MULTA,L_VAL_FECHA_GRABACION);
END;

END LOOP;
END;
/

EXEC PRO_PRESTAMO(3,2015);




