CREATE OR REPLACE PROCEDURE PL (CADENA VARCHAR2) AS
BEGIN
 DBMS_OUTPUT.PUT_LINE(CADENA);
END PL;
/

DECLARE

CURSOR C1 IS
SELECT *
FROM EMPLOYEES
WHERE SALARY <= 4500
ORDER BY EMPLOYEE_ID;

CURSOR C2 IS 
SELECT *
FROM RANGO_AUMENTO;


BEGIN
 FOR R1 IN C1 LOOP
      FOR R2 IN C2 LOOP
           IF R1.SALARY BETWEEN  R2.SALARIO_INFERIOR AND R2.SALARIO_SUPERIOR THEN
                INSERT INTO AUMENTO_SALARIO
                VALUES(R1.EMPLOYEE_ID, R1.SALARY, R1.SALARY*R2.PORC_AUMENTO , R1.SALARY*(1+R2.PORC_AUMENTO));
         END IF;
      END LOOP; 
      
IF R1.SALARY BETWEEN 3501 AND 3999 OR R1.SALARY > 4500 THEN 
INSERT INTO ERRORES_AUMENTO_SALARIOS
VALUES(R1.EMPLOYEE_ID, 'El salario ' || R1.SALARY || 
      ' no existe entre los rangos de la tabla RANGO AUMENTO ');
END IF;  
END LOOP;
END;

/













