CREATE OR REPLACE PROCEDURE PL (CADENA VARCHAR2) AS
BEGIN
 DBMS_OUTPUT.PUT_LINE(CADENA);
END PL;
/

DROP TABLE ERRORESORACLE;
CREATE TABLE ERRORESORACLE(

CODE NUMBER,
MESSAGE VARCHAR2(300)

);

DECLARE
L_CODIGO ERRORESORACLE.CODE%TYPE;
L_MENSAJE ERRORESORACLE.MESSAGE%TYPE;
BEGIN 
FOR I IN REVERSE -33420..0 LOOP
L_CODIGO := I;
L_MENSAJE := SUBSTR(SQLERRM(I), 11 , 300);
IF (SQLERRM(I) NOT LIKE '%Message % not found%') THEN
INSERT INTO ERRORESORACLE
VALUES(L_CODIGO, L_MENSAJE);
END IF;
END LOOP;
END;

/

SELECT *
FROM ERRORESORACLE 
ORDER BY CODE DESC;