
--1

CREATE OR REPLACE VIEW V_LIBRO AS
SELECT T.TITULO "NOMBRE DEL LIBRO" , AT.NOMBRE ||' '|| AT.APELLIDOS "AUTOR",
        UPPER(ED.DESCRIPCION) " EDITORIAL" , COUNT(EJ.TITULOID) "TOTAL EJEMPLARES",
       TO_CHAR(SUM(T.Precio),'$9G999G999') "MONTO TOTAL"
FROM EDITORIAL ED JOIN TITULO T  ON Ed.Editorialid = T.Editorialid 
               JOIN EJEMPLAR EJ ON T.TITULOID = Ej.TITULOID
              JOIN AUTOR AT ON Ej.Tituloid = At.Tituloid
GROUP BY T.TITULO, AT.NOMBRE ||' '|| AT.APELLIDOS, UPPER(ED.DESCRIPCION)
ORDER BY T.TITULO;

SELECT * FROM V_LIBRO;


--2

CREATE OR REPLACE VIEW V_MULTAS AS
SELECT UPPER(E.DESCRIPCION)"ESCUELA",C.DESCRIPCION "CARRERA",
       COUNT(P.ALUMNOID)"ALUMNOS CON PRESTAMOS",TO_CHAR(SUM(P.MULTA),'$999G999')"TOTAL MULTA"
FROM  PRESTAMO P JOIN ALUMNO A ON A.ALUMNOID = P.ALUMNOID
JOIN CARRERA C ON A.CARRERAID = C.CARRERAID
JOIN ESCUELA E ON C.ESCUELAID = E.ESCUELAID
WHERE A.ALUMNOID = P.ALUMNOID
GROUP BY E.DESCRIPCION,C.DESCRIPCION
ORDER BY E.DESCRIPCION,"TOTAL MULTA" DESC;

SELECT * FROM V_MULTAS;


--3
CREATE OR REPLACE VIEW V_PRESUP_LIBROS AS
SELECT T.TITULO NOMBRE_DEL_LIBRO, COUNT(P.PRESTAMOID)TOTAL_PRESTAMO,
CASE 
WHEN COUNT(P.PRESTAMOID) = 0 THEN 'Mantenerse presupuesto'
WHEN COUNT(P.PRESTAMOID) = 1 OR COUNT(P.PRESTAMOID) = 2 THEN 'Aumentar 5% en el presupuesto'
WHEN COUNT(P.PRESTAMOID) = 3 OR COUNT(P.PRESTAMOID) = 4 THEN 'Aumentar 10% en el presupuesto'
WHEN COUNT(P.PRESTAMOID) >4 THEN 'Aumentar 15% en el presupuesto'
END OBSERVACION_PRESUPUESTO
FROM TITULO T FULL JOIN PRESTAMO P ON T.TITULOID = P.TITULOID
WHERE P.FECHA_INICIO IS NULL OR EXTRACT(YEAR FROM P.FECHA_INICIO) = 2016
GROUP BY T.TITULO
ORDER BY TOTAL_PRESTAMO,T.TITULO;

SELECT * FROM V_PRESUP_LIBROS;

--4


CREATE OR REPLACE VIEW V_LIBRO AS
SELECT C.DESCRIPCION,
A.NOMBRE || ' '|| A.APATERNO ||' ' || A.AMATERNO "ALUMNO",
LOWER(SUBSTR(A.NOMBRE,1,1)||SUBSTR(A.APATERNO,-3)||EXTRACT(YEAR FROM A.FECHA_NACIMIENTO))||'@alumnoiptf.cl' "CORREO ALUMNO",
COUNT(P.PRESTAMOID)"LIBROS SOLICITADOS"
FROM PRESTAMO P FULL JOIN ALUMNO A ON P.ALUMNOID = A.ALUMNOID
JOIN CARRERA C ON A.CARRERAID = C.CARRERAID
GROUP BY A.NOMBRE || ' '|| A.APATERNO ||' ' || A.AMATERNO,
C.DESCRIPCION,
LOWER(SUBSTR(A.NOMBRE,1,1)||SUBSTR(A.APATERNO,-3)||EXTRACT(YEAR FROM A.FECHA_NACIMIENTO))||'@alumnoiptf.cl'
HAVING COUNT(P.PRESTAMOID) <= 2
ORDER BY C.DESCRIPCION;

SELECT * FROM V_LIBRO;


